### ISSUE TITLE
Multi Host

### ISSUE THREAD

**Issue by jeffutter** [gliderlabs/connectable#15]
I think I must be missing something here. I thought ambassadord would help communicate across multiple (coreos) hosts.

So far I have the following coreos services setup:

https://gist.github.com/jeffutter/422ce28865aff09464a1

With this setup I can do the following on either host and it works:

```bash
core@core-02 ~ $ docker run --rm --link backends:backends -e "BACKEND_6379=etcd://172.17.8.101:4001/services/redis/redis" -ti redis:2.8 bash -c 'redis-cli -h backends ping'
PONG
```

However, the following also works, removing the utility of ambassador all-together:

```bash
core@core-02 ~ $ docker run --rm -ti redis:2.8 redis-cli -h $(etcdctl get services/redis/redis | cut -d ':' -f 1) ping
PONG
```

I don't see the purpose of ambassador in this setup. I assumed ambassador might work in a fashion where my docker containers could talk to ambassador via the internal docker network. Containers on the the same host would hit the local ambassador and be routed to other containers on the same host as needed. Containers on remote hosts would hit their local ambassador, which would forward to the remote ambassador (port 10000) and then forward on to the internal docker networks. Am I missing something as to how this is supposed to work?

**Comment by jeffutter** [comment]
I may have just figured this out while waiting in line at the grocery store: this is the expected behavior. The purpose for using ambasadord is that if the locations of your services move after the consuming containers start, they can still be reachable with ambassadord. Otherwise you would need to restart your consuming service every time an underlying service changed.

To get a solution like I mentioned at the end, you would need to use something like weave.

Is this correct?

**Comment by progrium** [comment]
Project renamed to connectable, but yes if you want a magic *network* then you can use new Docker networking or Weave. All connectable does is provide a local proxy to services registered via service discovery.
