### ISSUE TITLE
Simple mode with --expose proxies on wrong port (10000 instead of same port as dest)

### ISSUE THREAD

**Issue by grossws** [gliderlabs/connectable#16]
If I run `docker run -d --name some-mongo --expose 27017 progrium/ambassadord mongo-host:27017`
port `10000` is proxied to `mongo-host:27017`, but port `27017` of this container is not.

`README.md` says "Ambassador to fixed/resolved backend(s) using domain or IP and port. Listens on same port as destination."

**Comment by progrium** [comment]
Simple mode was dropped in connectable.
