### ISSUE TITLE
Build the Latest Code

### ISSUE THREAD

**Issue by BugRoger** [gliderlabs/connectable#18]
We ran into #13 while using the latest Image pulled from Dockerhub. It looks like the latest code didn't make it into `stage/ambassadord` yet.

I tried to build it myself but my lacking Go karate together with our corporate proxy foiled that attempt. :(

Would you mind building the binary? Or give me a short rundown on how to gather all dependencies for building it?

**Comment by progrium** [comment]
Reworked into gliderlabs/connectable with latest release build set up ... however it's still early.
