### ISSUE TITLE
--setup-iptables : using a container named something besides "backends"

### ISSUE THREAD

**Issue by tysonnorris** [gliderlabs/connectable#20]
I can get omni mode working with my ambassadord container named backends. 

However if I change the name to something else, like "myservices", the --setup-iptables container fails (even when I change the name of the linked container to match "myservices"). 

Reverting my container name to "backends" makes the --setup-iptables container work again. 

I took a look at the code and it is not obvious to me where the "backends" container name becomes important. Some other names work, like "ba", but not "router" or "routes". 

I'm also using fig, so my container names are not even directly backends, but rather "mydir_backends_1".

Is there something I'm missing?
Thanks

**Comment by progrium** [comment]
Unfortunately I can't support this yet. We're going to fix it up soon, but
until then it's sort of provided as-is.

On Mon, Mar 23, 2015 at 6:22 PM, tysonnorris <notifications@github.com>
wrote:

> I can get omni mode working with my ambassadord container named backends.
>
> However if I change the name to something else, like "myservices", the
> --setup-iptables container fails (even when I change the name of the linked
> container to match "myservices").
>
> Reverting my container name to "backends" makes the --setup-iptables
> container work again.
>
> I took a look at the code and it is not obvious to me where the "backends"
> container name becomes important. Some other names work, like "ba", but not
> "router" or "routes".
>
> I'm also using fig, so my container names are not even directly backends,
> but rather "mydir_backends_1".
>
> Is there something I'm missing?
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/ambassadord/issues/20>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by antz29** [comment]
@progrium thanks for clarifying, could you maybe give some indication as to what "soon" means at all? are we talking days, weeks months or years? thanks!

**Comment by progrium** [comment]
Weeks to months. Depends on sponsorship closing and not having higher
priority projects, but interest/demand definitely puts pressure on it.

On Mon, Mar 30, 2015 at 5:26 AM, John Le Drew <notifications@github.com>
wrote:

> @progrium <https://github.com/progrium> thanks for clarifying, could you
> maybe give some indication as to what "soon" means at all? are we talking
> days, weeks months or years? thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/ambassadord/issues/20#issuecomment-87626533>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by adamkdean** [comment]
I have this working fine with the container called `ambassador` instead of `backends`.

When running the ambassador, use `--name ambassador`. When running the `--setup-iptables` container, use `--net container:ambassador`. Hope this helps.

P.S. you still have to called env variables `BACKEND_0000` etc.

**Comment by progrium** [comment]
Connectable does this now!
