### ISSUE TITLE
Ambassadord should launch the second container from the first in omni mode

### ISSUE THREAD

**Issue by virtuald** [gliderlabs/connectable#3]
Since you already have the docker socket, you can do this. See https://github.com/docker/docker/issues/7228#issuecomment-50185290.

This would make using ambassadord much easier. If you don't have the cycles to do this, I can take a look at it this weekend, perhaps this is a good time for me to finally learn go.

**Comment by stefanfoulis** [comment]
Just running setup iptables before ambassadord as part of the startup script worked fine for me.

``docker run --rm --privileged progrium/ambassadord --omnimode-and-setup-iptables`` with the following ``/start`` script:

```
#!/bin/bash

socat_from_link() {
	sed 's/.*_PORT_\([0-9]*\)_TCP=tcp:\/\/\(.*\):\(.*\)/socat TCP4-LISTEN:\1,fork,reuseaddr TCP4:\2:\3 \&/'
}

links() {
	echo "Running in links mode..."
	env | grep _TCP= | socat_from_link | echo -e "$(cat)\nwait" | bash
}

setup_iptables() {
	echo "Setting up iptables for container interface..."
	iptables -t nat -A PREROUTING -p tcp -j REDIRECT --to-ports 10000
}

omnimode_and_setup_iptables() {
	setup_iptables
	echo "Launching ambassadord in omnimode..."
	exec /bin/ambassadord
}

main() {
	case "$1" in
	--links)                            links;;
	--setup-iptables)                   setup_iptables;;
	--omnimode-and-setup-iptables)      omnimode_and_setup_iptables;;
	--omnimode)                         /bin/ambassadord;;
	*)                                  /bin/ambassadord "$1";;
	esac
}

main "$@"

```

I'm not sure how much difference it makes from a security point of view if the ambassadord container runs in privileged mode all the time... but you have the docker socket, so I guess you basically have root access anyway...

@progrium is this a change you'd merge? If so, I can make a proper pull request including documentation changes.

**Comment by progrium** [comment]
Normally i'd take the PR, but this project is about to be renamed and rewritten with this builtin. Readme is already written (no implementation just yet): https://github.com/progrium/ambassadord/tree/connectable

**Comment by progrium** [comment]
Done.
