### ISSUE TITLE
Ambassadord omni mode should have a default backend arg

### ISSUE THREAD

**Issue by virtuald** [gliderlabs/connectable#4]
For backends like etcd, typing in the backend name over and over again is tiresome and errorprone. Additionally, why should the container have to specify the servername?

So, if the backend environment variable starts with etcd:// or consul/etc, then it does the same thing that it does now. Otherwise, if its just a raw string, and --default-backend is set, then it appends the env variable to the key and does the lookup that way.

**Comment by progrium** [comment]
Connectable is now designed to work with a package called `lookup`, which resolves names. It can currently only be configured to have one resolver. So as I suggested before, you could a more advanced set up to support multiple resolvers. However, the old etcd provider was not ported to connectable yet...
