### ISSUE TITLE
implement DNS ttl

### ISSUE THREAD

**Issue by binocarlos** [gliderlabs/connectable#7]
Hey,

I'm wanting to use the consul service catalog with registrator not the key value store because of health checking and DNS goodness.

So I would run ambassadord with `BACKEND_8080=httptest.services.consul` to route to a service.

The really cool thing about the configBackends is the `.WatchToUpdate()` method because it caches the lookups.  The DNS is good for database connections but for lots of HTTP its better to have resolved routes in memory.

A useful thing would be an in memory cache that changes with the service catalog not the key/value store.

I'm thinking there could be a 4th type of backend - like a `srvBackends` but that has a `.WatchToUpdate()` method listening to `/v1/catalog/service/<service>`.

This way the same `consul:` registrator path is used for both but the user can choose between current srvBackends routing (for things like long-lived database connections) and cached service routing (for things like HTTP connections).

it could be: `BACKEND_8080=/httptest.services.consul` (or something similar) to denote that the service cache mode should be used

Do you think this is useful? I'm happy to make a pull request if you do :)

**Comment by progrium** [comment]
readme for new version of ambassadord coming: https://github.com/progrium/ambassadord/tree/connectable#readme

**Comment by binocarlos** [comment]
nice! I like the new name :-)

**Comment by progrium** [comment]
The new `lookup` package now that it's evolved into gliderlabs/connectable does perform 1s caching/TTL. It's not configurable yet, but should be.
